services:
  # db:
  #   image: postgres:15
  #   container_name: friends_db
  #   env_file:
  #     - .env-non-dev
  #   volumes:
  #     - postgresdata:/var/lib/postgresql/data
  #   ports:
  #     - 5433:5432

  bot:
    build:
      context: .
    container_name: friends_bot
    env_file:
      - .env-non-dev
    # depends_on:
    #   - db
    # command: ["/friends_bot/start.sh"]


# volumes:
#   postgresdata: