services:
  db:
    image: postgres:15
    container_name: notice_db
    env_file:
      - .env-non-dev
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgresdata: